"""Idempotent SEO transform for tjtkw site (健身体脂计算器). Re-runnable after WorkBuddy updates."""
HEAD_ADD = '<link rel="canonical" href="https://tjtkw.li00000.xyz/" />\n<meta name="keywords" content="体脂计算器,健身体脂率,标准体脂率,体脂率对照表,基础代谢率,BMR 公式,TDEE,Mifflin-St Jeor,减脂热量缺口,腰围身高比体脂估算" />\n<meta property="og:type" content="website" />\n<meta property="og:title" content="健身体脂计算器 · BMI / 体脂率 / BMR / TDEE 在线计算" />\n<meta property="og:description" content="基于 Mifflin-St Jeor 公式的在线健身计算工具：BMI、体脂率（Deurenberg 公式 + 腰围/身高比双通道）、基础代谢率 BMR、每日总消耗 TDEE，并自动给出 4–6 周减脂计划。" />\n<meta property="og:url" content="https://tjtkw.li00000.xyz/" />\n<meta property="og:site_name" content="健身体脂计算器" />\n<meta property="og:locale" content="zh_CN" />\n<meta name="twitter:card" content="summary" />\n<script type="application/ld+json">\n{"@context":"https://schema.org","@type":"WebApplication","name":"健身体脂计算器","alternateName":["体脂计算器","BMI 计算器","基础代谢率 BMR 计算器","TDEE 每日热量计算器"],"url":"https://tjtkw.li00000.xyz/","applicationCategory":"MedicalWebApplication","operatingSystem":"Any","inLanguage":"zh-CN","offers":{"@type":"Offer","price":"0","priceCurrency":"CNY"},"publisher":{"@type":"Organization","name":"li00000 在线工具集","url":"https://li00000.xyz/"}}\n</script>\n<script type="application/ld+json">\n{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[\n{"@type":"Question","name":"标准体脂率是多少？","acceptedAnswer":{"@type":"Answer","text":"按 ACSM 参考范围：男性 20–39 岁健康体脂率为 8%–19%，40–59 岁 11%–21%，60 岁以上 13%–24%；女性 20–39 岁 21%–32%，40–59 岁 23%–33%，60 岁以上 24%–35%。"}},\n{"@type":"Question","name":"体脂率怎么算？","acceptedAnswer":{"@type":"Answer","text":"常用两种：Deurenberg 公式（1.20×BMI − 0.23×年龄 − 5.4×性别 + 10.7，男=1 女=0）和腰围/身高比修正法，后者对肌肉量大的人更准确。"}},\n{"@type":"Question","name":"基础代谢率 BMR 怎么算？","acceptedAnswer":{"@type":"Answer","text":"Mifflin-St Jeor 公式：男性 BMR = 10×体重kg + 6.25×身高cm − 5×年龄 + 5；女性 = 10×体重 + 6.25×身高 − 5×年龄 − 161。"}},\n{"@type":"Question","name":"减脂期热量缺口多少合适？","acceptedAnswer":{"@type":"Answer","text":"每日 500–800 kcal 缺口（约每周减 0.5 公斤脂肪）比较稳妥，蛋白质按 1.6–2.2 g/kg 体重摄入以保留肌肉。"}}\n]}\n</script>\n'
SEO_BODY = '\n<section class="seo">\n  <h2>体脂率标准与常见问题</h2>\n  <h3>标准体脂率是多少（男 / 女 体脂率对照表）</h3>\n  <p>按 ACSM（美国运动医学会）参考范围：<b>男性</b> 20–39 岁健康体脂率为 8%–19%，40–59 岁 11%–21%，60 岁以上 13%–24%；<b>女性</b> 20–39 岁为 21%–32%，40–59 岁 23%–33%，60 岁以上 24%–35%。低于下限属于运动员或精瘦水平，高于上限则判定为体脂超标。健身入门期男性建议控制在 12%–17%、女性 18%–24% 之间，力量训练者保留更多体脂有利于恢复。</p>\n  <h3>体脂率怎么算？两种常用估算公式</h3>\n  <p>① <b>Deurenberg 公式</b>：体脂率(%) = 1.20×BMI − 0.23×年龄 − 5.4×性别 + 10.7（男性=1，女性=0），只靠身高体重就能估算；② <b>腰围/身高比修正法</b>：在 BMI 法结果上按腰围÷身高的位置做 −3.2%~+4.1% 修正，腰围小、肌肉量大的人估算更贴近真实值。本计算器未填腰围时自动走 ①，填了腰围切换到 ②。</p>\n  <h3>基础代谢率 BMR 和 TDEE 分别是什么？</h3>\n  <p><b>BMR（基础代谢率）</b>是静息状态下维持体温、呼吸、心跳等生命活动消耗的最低热量，用 Mifflin-St Jeor 公式计算：男性 BMR = 10×体重kg + 6.25×身高cm − 5×年龄 + 5，女性 −161。<b>TDEE（每日总能量消耗）</b> = BMR × 活动系数（久坐 1.2、轻度活动 1.375、中度 1.55、高度 1.725、重体力 1.9），TDEE 就是维持当前体重每天该吃进的热量，是减脂和增肌饮食方案的起点。</p>\n  <h3>减脂期热量缺口多少合适？蛋白质要吃多少？</h3>\n  <p>每公斤脂肪约含 7700 kcal，所以每日 500–800 kcal 的缺口对应每周减 0.5–0.8 公斤脂肪，属于可持续范围；缺口拉大到 1000 kcal 以上容易掉肌肉、降基础代谢、后期反弹快。蛋白质按 1.6–2.2 g/kg 体重摄入（减脂期取上限），训练日可在碳水上补一点。减脂末期把缺口减半、安排每周 1 天自由饮食日，是防反弹的标准做法。</p>\n  <h3>腰围多少算危险？</h3>\n  <p>按 WHO 亚太标准，<b>男性腰围 ≥ 90 cm、女性 ≥ 80 cm</b> 即为中心性（腹型）肥胖，心血管和代谢风险显著升高；另一条简易线是腰围/身高比 0.5——腰围达到身高一半就要重视。减脂计划里监测腰围比盯体重更反映脂肪变化。</p>\n  <h2>体脂率参考与延伸阅读</h2>\n  <ul class="seo-links">\n    <li>Mayo Clinic · 体脂率参考值：<a href="https://www.mayoclinic.org/healthy-lifestyle/fitness/in-depth/body-fat-percentile/art-20045195" target="_blank" rel="noopener">body fat percentile</a></li>\n    <li>Harvard Health · 正常体脂百分比：<a href="https://www.health.harvard.edu/publications/what-s-normal-body-fat-percentage" target="_blank" rel="noopener">what\'s normal body fat percentage</a></li>\n    <li>ExRx.net · Mifflin 公式与每日热量消耗：<a href="https://www.exrx.net/WeightLoss/CalorieExpenditure" target="_blank" rel="noopener">Calorie Expenditure</a></li>\n    <li>WHO · 肥胖与体成分：<a href="https://www.who.int/health-topics/obesity" target="_blank" rel="noopener">Obesity</a></li>\n  </ul>\n  <p class="friend">更多在线工具：<a href="https://li00000.xyz/">在线PS 修图</a> · <a href="https://tools.li00000.xyz/">房贷计算器</a> · <a href="https://blog.li00000.xyz/">养老生活博客</a> · <a href="https://ligcli.com/">ligcli</a></p>\n  <p class="fine">本页计算结果基于通用公式估算，不替代医生或注册营养师的个体化建议。</p>\n</section>\n<style>\n.seo{max-width:1120px;margin:24px auto 48px;padding:0 20px;font-size:15px;color:#33504a}\n.seo h2{font-size:20px;color:#0f241b;margin:26px 0 10px}\n.seo h3{font-size:16px;color:#14532d;margin:18px 0 6px}\n.seo p{line-height:1.7}\n.seo-links{padding-left:20px;margin:8px 0}\n.seo-links a{color:#166534}\n.friend{margin-top:22px;font-size:13px;color:#6b857d;border-top:1px solid #d6ebe0;padding-top:14px}\n.friend a{color:#166534}\n.fine{font-size:12px;color:#6b857d;margin-top:8px}\n</style>\n'

def transform(h):
    if 'rel="canonical"' in h:
        return h
    h = h.replace('<meta name="viewport"', HEAD_ADD + '\n<meta name="viewport"', 1)
    h = h.replace('</body>', SEO_BODY + '\n</body>', 1)
    return h
